"""
Application domain model representing `tribe_applications` database table.
"""
from datetime import date, datetime
from typing import Optional
from pydantic import BaseModel, ConfigDict, Field


class Application(BaseModel):
    """
    Model representation of `tribe_applications` table record.
    Matches database schema and foreign key relationships.
    """
    model_config = ConfigDict(from_attributes=True)

    id: Optional[str] = Field(default=None, description="Internal UUID primary key generated by PostgreSQL")
    application_id: str = Field(..., description="Unique Business ID (e.g. TRB-APP-000001)")
    student_id: str = Field(..., description="UUID reference to tribe_students.id")
    scholarship_id: str = Field(..., description="UUID reference to tribe_scholarships.id")
    institution_id: Optional[str] = Field(default=None, description="UUID reference to tribe_institutions.id")
    academic_year: str = Field(..., description="Academic year (e.g. 2026-27)")
    application_date: Optional[date] = Field(default=None, description="Date application was initiated")
    status: str = Field(default="DRAFT", description="Application status (e.g. DRAFT, SUBMITTED, UNDER_VERIFICATION, SANCTIONED, REJECTED)")
    current_stage: str = Field(default="APPLICATION", description="Current workflow stage (e.g. APPLICATION, INSTITUTION_VERIFICATION, STATE_VERIFICATION, DISBURSEMENT)")
    submitted_at: Optional[datetime] = Field(default=None, description="Timestamp of submission")
    sanctioned_at: Optional[datetime] = Field(default=None, description="Timestamp of sanction")
    rejected_at: Optional[datetime] = Field(default=None, description="Timestamp of rejection")
    rejection_reason: Optional[str] = Field(default=None, description="Detailed explanation if rejected")
    created_at: Optional[datetime] = Field(default=None, description="Record creation timestamp")
    updated_at: Optional[datetime] = Field(default=None, description="Record update timestamp")
