"""
Document domain model representing `tribe_documents` database table.
"""
from datetime import date, datetime
from typing import Optional
from pydantic import BaseModel, ConfigDict, Field


class Document(BaseModel):
    """
    Model representation of `tribe_documents` table record.
    Matches exact database columns.
    """
    model_config = ConfigDict(from_attributes=True)

    id: Optional[str] = Field(default=None, description="UUID primary key generated by PostgreSQL")
    document_id: str = Field(..., description="Unique Business ID (e.g. TRB-DOC-000001)")
    student_id: str = Field(..., description="UUID reference to tribe_students.id")
    document_type: str = Field(..., description="Type of document (e.g. CASTE_CERTIFICATE, INCOME_CERTIFICATE)")
    document_name: str = Field(..., description="Human-readable title/label of the document")
    file_url: Optional[str] = Field(default=None, description="Accessible URL or storage link to the file")
    storage_path: Optional[str] = Field(default=None, description="Bucket/storage path for the file")
    file_size: Optional[int] = Field(default=None, description="File size in bytes")
    file_type: Optional[str] = Field(default=None, description="MIME type (e.g. application/pdf, image/jpeg)")
    document_number: Optional[str] = Field(default=None, description="Official certificate or document registration number")
    expiry_date: Optional[date] = Field(default=None, description="Document expiry date if applicable")
    is_active: bool = Field(default=True, description="Active status flag")
    created_at: Optional[datetime] = Field(default=None, description="Creation timestamp")
    updated_at: Optional[datetime] = Field(default=None, description="Last update timestamp")
