"""
Institution domain model representing `tribe_institutions` database table.
"""
from datetime import datetime
from typing import Optional
from pydantic import BaseModel, ConfigDict, Field


class Institution(BaseModel):
    """
    Model representation of `tribe_institutions` table record.
    """
    model_config = ConfigDict(from_attributes=True)

    id: Optional[str] = Field(default=None, description="Internal UUID primary key generated by PostgreSQL")
    institution_id: Optional[str] = Field(default=None, description="Unique Business ID (e.g. TRB-INS-000001)")
    name: Optional[str] = Field(default=None, description="Institution / School / College name")
    code: Optional[str] = Field(default=None, description="AISHE / DISE / Board Code")
    institution_type: Optional[str] = Field(default=None, description="Type of institution (School, College, University)")
    state: Optional[str] = Field(default=None, description="State location")
    district: Optional[str] = Field(default=None, description="District location")
    is_active: bool = Field(default=True, description="Active status flag")
    created_at: Optional[datetime] = Field(default=None, description="Creation timestamp")
    updated_at: Optional[datetime] = Field(default=None, description="Last update timestamp")
