"""
Notification domain model representing `tribe_notifications` database table.
"""
from datetime import datetime
from typing import Optional
from pydantic import BaseModel, ConfigDict, Field


class Notification(BaseModel):
    """
    Model representation of `tribe_notifications` table record.
    Matches database schema and foreign key relationships.
    """
    model_config = ConfigDict(from_attributes=True)

    id: Optional[str] = Field(default=None, description="UUID primary key generated by PostgreSQL")
    student_id: str = Field(..., description="UUID reference to tribe_students.id")
    title: str = Field(..., description="Notification title / heading")
    message: str = Field(..., description="Notification content / body message")
    notification_type: str = Field(default="GENERAL", description="Notification category (e.g. APPLICATION, DOCUMENT, VERIFICATION, PAYMENT, SYSTEM, GENERAL)")
    is_read: bool = Field(default=False, description="Read state flag")
    application_id: Optional[str] = Field(default=None, description="UUID reference to tribe_applications.id if linked")
    sent_at: Optional[datetime] = Field(default=None, description="Timestamp when notification was dispatched")
    created_at: Optional[datetime] = Field(default=None, description="Creation timestamp")
