"""
Payment domain model representing `tribe_disbursements` database table.
"""
from datetime import datetime
from typing import Optional
from pydantic import BaseModel, ConfigDict, Field


class Payment(BaseModel):
    """
    Model representation of `tribe_disbursements` table record.
    Matches database schema and foreign key relationships.
    """
    model_config = ConfigDict(from_attributes=True)

    id: Optional[str] = Field(default=None, description="Internal UUID primary key generated by PostgreSQL")
    payment_id: str = Field(..., description="Unique Business ID (e.g. TRB-PAY-000001)")
    application_id: str = Field(..., description="UUID reference to tribe_applications.id")
    student_id: str = Field(..., description="UUID reference to tribe_students.id")
    amount: float = Field(..., description="Disbursement amount in INR")
    payment_status: str = Field(default="PENDING", description="Payment status (e.g. PENDING, PROCESSING, SUCCESS, FAILED)")
    transaction_reference: Optional[str] = Field(default=None, description="Transaction Reference number")
    utr_number: Optional[str] = Field(default=None, description="Bank UTR number")
    payment_date: Optional[datetime] = Field(default=None, description="Payment disbursement timestamp")
    bank_name: Optional[str] = Field(default=None, description="Disbursing or Beneficiary Bank Name")
    failure_reason: Optional[str] = Field(default=None, description="Failure reason if transaction failed")
    created_at: Optional[datetime] = Field(default=None, description="Creation timestamp")
    updated_at: Optional[datetime] = Field(default=None, description="Last update timestamp")
