"""
Scholarship domain model representing `tribe_scholarships` database table.
"""
from datetime import datetime
from typing import Optional
from pydantic import BaseModel, ConfigDict, Field


class Scholarship(BaseModel):
    """
    Model representation of `tribe_scholarships` table record.
    Matches database schema and column names.
    """
    model_config = ConfigDict(from_attributes=True)

    id: Optional[str] = Field(default=None, description="Internal UUID primary key generated by PostgreSQL")
    scholarship_id: str = Field(..., description="Unique Business ID (e.g. TRB-SCH-000001)")
    name: str = Field(..., description="Full scholarship scheme title")
    short_name: str = Field(..., description="Scholarship scheme code name (e.g. PRE_MATRIC, POST_MATRIC)")
    description: Optional[str] = Field(default=None, description="Detailed description of the scheme")
    scholarship_type: Optional[str] = Field(default=None, description="Scheme category type (e.g. PRE_MATRIC, POST_MATRIC, TOP_CLASS, HIGHER_EDUCATION, OVERSEAS)")
    provider: Optional[str] = Field(default="Ministry of Tribal Affairs", description="Granting entity / Ministry")
    is_active: bool = Field(default=True, description="Active status flag")
    created_at: Optional[datetime] = Field(default=None, description="Creation timestamp")
    updated_at: Optional[datetime] = Field(default=None, description="Last update timestamp")
