"""
Student domain model representing the existing `tribe_students` database table.
"""
from datetime import date, datetime
from typing import Optional
from uuid import UUID
from pydantic import BaseModel, ConfigDict, Field


class Student(BaseModel):
    """
    Model representation of `tribe_students` table record.
    Matches exact database column names.
    """
    model_config = ConfigDict(from_attributes=True)

    id: Optional[str] = Field(default=None, description="UUID primary key generated by PostgreSQL")
    student_id: Optional[str] = Field(default=None, description="Unique Business ID (e.g. TRB-STU-000001)")
    auth_user_id: str = Field(..., description="Supabase auth.users UUID reference")
    otr_id: Optional[str] = Field(default=None, description="One Time Registration ID")
    full_name: str = Field(..., description="Student full name")
    date_of_birth: Optional[date] = Field(default=None, description="Date of birth")
    gender: Optional[str] = Field(default=None, description="Gender (e.g. Male, Female, Other)")
    mobile_number: Optional[str] = Field(default=None, description="Mobile contact number")
    email: str = Field(..., description="Student email address")
    tribal_category: Optional[str] = Field(default=None, description="Tribal category / PVTG identifier")
    state: Optional[str] = Field(default=None, description="State of domicile")
    district: Optional[str] = Field(default=None, description="District of domicile")
    is_active: bool = Field(default=True, description="Active status flag")
    created_at: Optional[datetime] = Field(default=None, description="Creation timestamp")
    updated_at: Optional[datetime] = Field(default=None, description="Last update timestamp")
