"""
Verification domain models representing `tribe_document_verifications` and `tribe_verifications` database tables.
"""
from datetime import datetime
from typing import Optional
from pydantic import BaseModel, ConfigDict, Field


class DocumentVerification(BaseModel):
    """
    Model representation of `tribe_document_verifications` table record.
    """
    model_config = ConfigDict(from_attributes=True)

    id: Optional[str] = Field(default=None, description="UUID primary key generated by PostgreSQL")
    document_id: str = Field(..., description="UUID reference to tribe_documents.id")
    verification_status: str = Field(default="PENDING", description="Status (PENDING, VERIFIED, REJECTED, FLAGGED)")
    verified_at: Optional[datetime] = Field(default=None, description="Timestamp of verification")
    verified_by: Optional[str] = Field(default=None, description="Verifier ID / Officer identifier")
    remarks: Optional[str] = Field(default=None, description="Verification remarks / notes")
    created_at: Optional[datetime] = Field(default=None, description="Creation timestamp")
    updated_at: Optional[datetime] = Field(default=None, description="Last update timestamp")


class ApplicationVerification(BaseModel):
    """
    Model representation of `tribe_verifications` table record (Application level verification).
    """
    model_config = ConfigDict(from_attributes=True)

    id: Optional[str] = Field(default=None, description="UUID primary key generated by PostgreSQL")
    application_id: str = Field(..., description="UUID reference to tribe_applications.id")
    status: str = Field(default="PENDING", description="Status (PENDING, IN_PROGRESS, APPROVED, REJECTED, FLAGGED)")
    verified_by: Optional[str] = Field(default=None, description="Verifier ID / Officer identifier")
    verification_level: Optional[str] = Field(default=None, description="Level (INSTITUTION, STATE, MINISTRY, OFFICER)")
    remarks: Optional[str] = Field(default=None, description="Verification remarks / notes")
    created_at: Optional[datetime] = Field(default=None, description="Creation timestamp")
    updated_at: Optional[datetime] = Field(default=None, description="Last update timestamp")
